project:
  type: website
  resources: 
    - CNAME
    - images
  
website:
  title: "NIM-ACh"
  favicon: "logos/logo.png"
  google-analytics: "G-KY2CTTZXHG"
  twitter-card: true
  open-graph:
    locale: es_ES
    site-name: NIM-ACh
  page-footer: 
    border: false
    left: "© 2024 NIM-ACh Group"
    right: 
      - icon: github
        href: https://github.com/NIM-ACh
      - icon: twitter 
        href: https://twitter.com/nimach_group
      - icon: instagram 
        href: https://www.instagram.com/nimach_group/
      - icon: fa-brands fa-researchgate
        href: https://www.researchgate.net/lab/Austral-Integrative-Neurophysiology-Group-Cristian-Nunez-Espinosa/
  navbar:
    logo: "logos/navbar.png"
    search: true
    right:
      - file: investigacion.qmd
        text: "Investigación"
      - file: personas.qmd
        text: "Personas"
      - file: publicaciones.qmd
        text: "Publicaciones"
      - file: dei.qmd
        text: "DEI"
      - file: contactanos.qmd
        text: "Contáctanos"

format:
  html:
    anchor-sections: true
    theme:
      light: flatly
    css: styles.css
    toc: true

lang: es

editor: source
